
spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

jwt:
  issuer: test@gmail.com
  secret_key: study-springboot
